name: Notion Commit

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Get GitHub Commit ID
      id: commit_id
      run: echo "::set-output name=commit_id::$(git log -1 --pretty=format:'%H')"

    - name: Extract Task ID
      id: extract_task_id
      run: |
        COMMIT_MSG=$(git log -1 --pretty=format:'%s')
        TASK_ID=$(echo $COMMIT_MSG | grep -o 'SHO-[0-9]*')
        echo "::set-output name=task_id::${TASK_ID##SHO-}"