name: Update Notion with GitHub Commit

on:
  push:
    branches:
      - develop

jobs:
  update-notion:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get GitHub Commit ID
      id: commit_id
      run: echo "::set-output name=commit_id::$(git log -1 --pretty=format:'%H')"

    - name: Extract Task ID
      id: extract_task_id
      run: |
        COMMIT_MSG=$(git log -1 --pretty=format:'%s')
        if [[ $COMMIT_MSG =~ SHO-([0-9]+) ]]; then
          TASK_ID=${BASH_REMATCH[1]}
        else
          TASK_ID=""
        fi
        echo "::set-output name=task_id::${TASK_ID}"

    - name: Check if Task exists in Notion
      id: check_notion_task
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        DATABASE_ID: "${{ secrets.NOTION_DB }}"
        TASK_ID: ${{ steps.extract_task_id.outputs.task_id }}
      run: |
        if [ -z "$TASK_ID" ]; then
          echo "::set-output name=task_exists::false"
        else
          JSON='{
            "filter": {
              "property": "ID",
              "number": {
                "equals": '$TASK_ID'
              }
            }
          }'
          response=$(curl -s -X POST "https://api.notion.com/v1/databases/$DATABASE_ID/query" \
            -H "Authorization: Bearer $NOTION_TOKEN" \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            --data "$JSON")
          
          PAGE_ID=$(echo "$response" | jq -r '.results[0].id')
          
          if [ -z "$PAGE_ID" ]; then
            echo "::set-output name=task_exists::false"
          else
            echo "::set-output name=task_exists::true"
            echo "::set-output name=page_id::$PAGE_ID"
          fi
        fi

    - name: Create Task in Notion
      if: steps.check_notion_task.outputs.task_exists == 'false'
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        DATABASE_ID: "${{ secrets.NOTION_DB }}"
        COMMIT_ID: ${{ steps.commit_id.outputs.commit_id }}
        TASK_NAME: $(git log -1 --pretty=format:'%s')
      run: |
        JSON='{
          "parent": {
            "database_id": "'$DATABASE_ID'"
          },
          "properties": {
            "Task name": {
              "title": [
                {
                  "text": {
                    "content": "'"$TASK_NAME"'"
                  }
                }
              ]
            },
            "GitHub Commit": {
              "rich_text": [
                {
                  "text": {
                    "content": "'"$COMMIT_ID"'"
                  }
                }
              ]
            }
          }
        }'
        curl -X POST "https://api.notion.com/v1/pages" \
          -H "Authorization: Bearer $NOTION_TOKEN" \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28" \
          --data "$JSON"

    - name: Get Existing GitHub Commits from Notion
      if: steps.check_notion_task.outputs.task_exists == 'true'
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        PAGE_ID: ${{ steps.check_notion_task.outputs.page_id }}
      run: |
        response=$(curl -s -X GET "https://api.notion.com/v1/pages/$PAGE_ID" \
          -H "Authorization: Bearer $NOTION_TOKEN" \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28")
        
        EXISTING_COMMITS=$(echo "$response" | jq -r '.properties."GitHub Commit".rich_text[0].text.content')
        NEW_COMMIT="${{ steps.commit_id.outputs.commit_id }}"
        
        if [ -z "$EXISTING_COMMITS" ]; then
          ALL_COMMITS="$NEW_COMMIT"
        else
          ALL_COMMITS="$EXISTING_COMMITS, $NEW_COMMIT"
        fi
        
        echo "::set-output name=all_commits::$ALL_COMMITS"

    - name: Update Existing Task in Notion with Concatenated Commits
      if: steps.check_notion_task.outputs.task_exists == 'true'
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        PAGE_ID: ${{ steps.check_notion_task.outputs.page_id }}
        ALL_COMMITS: ${{ steps.get_existing_commits.outputs.all_commits }}
      run: |
        JSON='{
          "properties": {
            "GitHub Commit": {
              "rich_text": [
                {
                  "text": {
                    "content": "'"$ALL_COMMITS"'"
                  }
                }
              ]
            }
          }
        }'
        
        curl -X PATCH "https://api.notion.com/v1/pages/$PAGE_ID" \
          -H "Authorization: Bearer $NOTION_TOKEN" \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28" \
          --data "$JSON"
