name: Notion Commit

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Get GitHub Commit ID
      id: commit_id
      run: echo "::set-output name=commit_id::$(git log -1 --pretty=format:'%H')"

    - name: Extract Task ID
      id: extract_task_id
      run: |
        COMMIT_MSG=$(git log -1 --pretty=format:'%s')
        TASK_ID=$(echo $COMMIT_MSG | grep -o 'SHO-[0-9]*')
        echo "::set-output name=task_id::${TASK_ID##SHO-}"

    - name: Query Notion Database
      id: query_notion
      run: |
        TASK_ID=$(echo "${{ steps.extract_task_id.outputs.task_id }}")
        curl --request POST \
          --url https://api.notion.com/v1/databases/${{ secrets.NOTION_DB }}/query \
          --header "Authorization: Bearer ${{ secrets.NOTION_API_KEY }}" \
          --header 'Content-Type: application/json' \
          --header 'Notion-Version: 2022-06-28' \
          --data '{
            "filter": {
              "property": "ID",
              "number": {
                "equals": $TASK_ID
              }
            }
          }'

   - name: Update Notion with GitHub Commit
      if: steps.query_notion.outputs.results != '[]'
      run: |
        PAGE_ID=$(echo "${{ steps.query_notion.outputs.results }}" | jq -r '.results[0].id')
        COMMIT_ID=$(echo "${{ steps.commit_id.outputs.commit_id }}")
        curl --request PATCH \
          --url "https://api.notion.com/v1/pages/$PAGE_ID" \
          --header "Authorization: Bearer ${{ secrets.NOTION_API_KEY }}" \
          --header 'Content-Type: application/json' \
          --header 'Notion-Version: 2022-06-28' \
          --data '{
            "properties": {
              "GitHub Commit": {
                "rich_text": [
                  {
                    "text": {
                      "content": "'"$COMMIT_ID"'"
                    }
                  }
                ]
              }
            }
          }'
